Adds vim plugin upgrades

diff --git a/vim/bundle/ale/run-tests b/vim/bundle/ale/run-tests
--- a/vim/bundle/ale/run-tests
+++ b/vim/bundle/ale/run-tests
@@ -55,6 +55,12 @@ while [ $# -ne 0 ]; do
         run_custom_checks=0
         shift
     ;;
+    --custom-checks-only)
+        run_vim_tests=0
+        run_neovim_tests=0
+        run_vint=0
+        shift
+    ;;
     --)
         shift
         break
@@ -75,6 +81,9 @@ if [ $# -ne 0 ]; then
     # have spaces in the names.
     tests="$*"
 fi
+
+# Delete .swp files in the test directory, which cause Vim 8 to hang.
+find test -name '*.swp' -delete
 
 docker images -q w0rp/ale | grep "^$CURRENT_IMAGE_ID" > /dev/null \
     || docker pull "$IMAGE"
@@ -200,7 +209,7 @@ if ((run_custom_checks)); then
     echo
 
     set -o pipefail
-    docker run -a stdout "${DOCKER_FLAGS[@]}" ./custom-checks . || EXIT=$?
+    docker run -a stdout "${DOCKER_FLAGS[@]}" test/script/custom-checks . || EXIT=$?
     set +o pipefail
     echo
 
@@ -211,6 +220,48 @@ if ((run_custom_checks)); then
     echo
 
     grep --exclude=tags -roh '\*.*\*$' doc | sort | uniq -d || EXIT=$?
+
+    echo '========================================'
+    echo 'Checking for invalid tag references'
+    echo '========================================'
+    echo 'Invalid tag references tags follow:'
+    echo
+
+    tag_regex='[gb]\?:\?\(ale\|ALE\)[a-zA-Z_\-]\+'
+
+    # Grep for tags and references, and complain if we find a reference without
+    # a tag for the reference. Only our tags will be included.
+    diff -u \
+        <(grep --exclude=tags -roh "\*$tag_regex\*" doc | sort -u | sed 's/*//g') \
+        <(grep --exclude=tags -roh "|$tag_regex|" doc | sort -u | sed 's/|//g') \
+        | grep '^+[^+]' && EXIT=1
+
+    echo '========================================'
+    echo 'diff README.md and doc/ale.txt tables'
+    echo '========================================'
+    echo 'Differences follow:'
+    echo
+
+    test/script/check-supported-tools-tables || EXIT=$?
+
+    echo '========================================'
+    echo 'Look for badly aligned doc tags'
+    echo '========================================'
+    echo 'Badly aligned tags follow:'
+    echo
+
+    # Documentation tags need to be aligned to the right margin, so look for
+    # tags which aren't at the right margin.
+    grep ' \*[^*]\+\*$' doc/ -r \
+        | awk '{ sep = index($0, ":"); if (length(substr($0, sep + 1 )) < 79) { print } }' \
+        | grep . && EXIT=1
+
+    echo '========================================'
+    echo 'Look for table of contents issues'
+    echo '========================================'
+    echo
+
+    test/script/check-toc || EXIT=$?
 fi
 
 exit $EXIT
